### ISSUE TITLE
Cloned Portfolio

### ISSUE THREAD

**Issue by nckhang** [TheRealmOfTheGeek/create-a-basic-portfolio-KragleBusters#1]
Hey, can I ask why you cloned by portfolio repo? This repo still has all my commit history, as well as copyrighted images. I'd really like if you removed this, since my portfolio repo does not have a license that does not allow you to reproduce, distribute, or create derivative works. Thanks.

**Comment by kvizdos** [comment]
@nckhang yes! Sorry, it's a project I wanted to do, but then forgot to follow up! I will remove this project as soon as I get back to my PC (around 5-10mins)!! I'm sooooo sorry!!!! Great portfolio, btw!
